### ISSUE TITLE
jquery isn't loading

### ISSUE THREAD

**Issue by bsiddiqui** [KartikTalwar/gmail-chrome-extension-boilerplate#5]
If I load this boilerplate up as is, I get this error: 
```js
Uncaught TypeError: Cannot read property 'extend' of undefined
```

Looks like jquery isn't loading before gmail.js needs it

**Comment by KartikTalwar** [comment]
@bsiddiqui can I know how you are installing/loading it? I've tested it on 4+ accounts and 3 browsers with no issues

**Comment by bsiddiqui** [comment]
@KartikTalwar just cloned it and loaded it as an unpacked extension, went to gmail, and opened console

**Comment by KartikTalwar** [comment]
Fascinating. Would it be possible for you to paste a screenshot of the console? My best guess is that some other extension is interfering with it. It might be worth checking if jquery already exists in gmail (from another ext) before loading this boilerplate. You should also try typing `gmail` in the console to confirm if it ends up eventually loading gmail.js

**Comment by bsiddiqui** [comment]
Yeah I think you're right - I disabled a few extensions and it started working. I think the culprit was Boomerang
